name = "danmu-api2"  # Worker 名称，可自定义
main = "danmu_api/worker.js"  # 入口文件路径（Workers 会导出 fetch 处理程序）
compatibility_date = "2025-09-13"  # 使用当前日期或更高，确保兼容最新 API

# Node.js 兼容性标志（必需，用于 Express 和 process.env）
[compatibility_flags]
nodejs_compat = true
enable_nodejs_http_server_modules = true  # 支持 node:http server API，用于 Express

# 构建步骤：安装依赖并构建（如果有 TypeScript 或其他构建需求）
[build]
command = "npm install"  # 简单安装依赖；如果有构建脚本，可改为 "npm run build"

# 环境变量（文本类型，直接在代码中使用 process.env.TOKEN）
[vars]
NODE_ENV = "production"  # 可选，默认值

# 触发器（可选，如果有定时任务）
[[triggers]]
crons = []  # 示例：["0 0 * * *"] 用于每日触发

# 环境（可选，用于不同环境如 dev/prod）
[env.production]
# 生产环境特定配置