name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # 你可以根据需要更改为你自己的默认分支
  pull_request:
    branches:
      - main   # 同样，你可以根据需要更改为你自己的默认分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 读取 version 文件并设置版本号
      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat danmu_api/version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 设置 Docker 镜像缓存（可选，加速构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 构建 Docker 镜像，并使用 version 作为标签
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/huangxd/danmu-api:${{ env.VERSION }} .

      # 推送 Docker 镜像到 GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/huangxd/danmu-api:${{ env.VERSION }}
