name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 读取 version 文件并设置版本号
      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat danmu_api/version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 设置 Docker 镜像缓存（可选，加速构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建 Docker 镜像，并使用 version 作为标签
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/danmu-api:${{ env.VERSION }} .

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/danmu-api:${{ env.VERSION }}